[workspace]
members = ["utils", "emu6809","gazm", "diss"]
resolver = "2"

[profile.release]
debug = true

[profile.final]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

