[workspace]
members = ["gazm", "makehelp"]
resolver = "2"

[profile.release]
debug = true

[profile.final]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = false
opt = 3
overflow-checks = false
prefer-dynamic = false

