[package]
name = "gazm"
version = "0.9.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
nom_locate = "*"
lazy_static = "1.4.0"
pretty_assertions="*"
emu = {path = "../emu"}
clap = { version = "3.1.5", features = ["derive", "color"] }
colored = "2"
ego-tree="*"
anyhow="*"
thiserror="*"
regex="*"
sha1="*"


serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
serde_json = "*"

futures="*"
async-std="*"
rayon = "1.5"

toml="*"

