[package]
name = "gazm"
version = "0.9.6"
edition = "2021"


[dependencies]
emu = {path = "../emu"}

nom = "*"
nom_locate = "*"

lazy_static = "1.4.0"
pretty_assertions="*"
clap = { version = "3.1.5", features = ["derive", "color"] }
colored = "2"
ego-tree="*"
anyhow="*"
thiserror="*"
regex="*"

serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
serde_json = "*"

futures="*"
async-std="*"
rayon = "1.5"
toml="*"
log="*"
env_logger="*"
simple-logging="*"

tokio-util = { version = "0.7", optional = true, features = ["codec"] }
tokio = { version = "1.21.0", features = ["full"] }
tower-lsp = { git = "https://github.com/gazliddon/tower-lsp", version = "*" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name="tokenize"
harness = false

